[package]
name = "chip-8"
version = "1.0.1"
authors = ["crowlkats"]
edition = "2018"

[dependencies]
rand = "0.8.3"
winit = "0.24.0"
wgpu = "0.7.1"
clap = "3.0.0-beta.2"
futures = "0.3.13"
anyhow = "1.0.40"
wgpu-subscriber = "0.1"
bytemuck = { version = "1.5.1", features = ["derive"] }
